version: "3.1"
services:
  api:
    image: torimbj/hng9:devops-django-react-task_api
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    command: python manage.py runserver 0.0.0.0:8000
    restart: always

  frontend:
    image: torimbj/hng9:devops-django-react-task_web
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    # command: npm run build
